

install.packages("tidyverse")
install.packages("janitor")
install.packages("report")
install.packages("ggplot2movies")
install.packages("gt")
install.packages("ggrepel")
install.packages("here")
install.packages("ggridges")
install.packages("patchwork")
install.packages("forcats")
install.packages("tools")

library(tidyverse)
library(janitor)
library(report)
library(ggplot2movies)
library(gt)
library(ggrepel)
library(here)
library(ggridges)
library(patchwork)
library(forcats)
library(tools)